<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7a1a1a8c0b822faf07563561bc8dcab2
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LeanCloud\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LeanCloud\\' => 
        array (
            0 => __DIR__ . '/..' . '/leancloud/leancloud-sdk/src/LeanCloud',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7a1a1a8c0b822faf07563561bc8dcab2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7a1a1a8c0b822faf07563561bc8dcab2::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
